// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

//! Canonical encoding golden vectors generated by tools/gen_golden.py.

use otel_arrow_dfe_series_lake::canonical::{
    Descriptor, MetricDescriptor, MetricKind, Signal, Temporality, canonical_bytes, hex, series_id,
};
use otel_arrow_dfe_series_lake::value::Value;

fn value_from_json(j: &serde_json::Value) -> Value {
    match j["type"].as_str().expect("type") {
        "null" => Value::Null,
        "str" => Value::Str(j["value"].as_str().expect("str").to_string()),
        "bytes" => Value::Bytes(hex_decode(j["value"].as_str().expect("hex"))),
        "int" => Value::Int(j["value"].as_i64().expect("int")),
        "double" => match j.get("bits") {
            Some(bits) => Value::Double(f64::from_bits(bits.as_u64().expect("bits"))),
            None => Value::Double(j["value"].as_f64().expect("double")),
        },
        "bool" => Value::Bool(j["value"].as_bool().expect("bool")),
        "array" => Value::Array(
            j["items"]
                .as_array()
                .expect("items")
                .iter()
                .map(value_from_json)
                .collect(),
        ),
        "kvlist" => Value::KvList(kv_from_json(&j["entries"])),
        other => panic!("unknown type {other}"),
    }
}

fn kv_from_json(j: &serde_json::Value) -> Vec<(String, Value)> {
    let mut v: Vec<(String, Value)> = j
        .as_array()
        .map(|a| {
            a.iter()
                .map(|e| {
                    (
                        e["key"].as_str().expect("key").to_string(),
                        value_from_json(&e["value"]),
                    )
                })
                .collect()
        })
        .unwrap_or_default();
    v.sort_by(|a, b| a.0.as_bytes().cmp(b.0.as_bytes()));
    v
}

fn hex_decode(s: &str) -> Vec<u8> {
    ::hex::decode(s).expect("hex")
}

fn str_field(j: &serde_json::Value, k: &str) -> String {
    j.get(k).and_then(|v| v.as_str()).unwrap_or("").to_string()
}

fn descriptor_from_json(j: &serde_json::Value) -> Descriptor {
    let signal = match j["signal"].as_str().expect("signal") {
        "logs" => Signal::Logs,
        _ => Signal::Metrics,
    };
    let metric = j.get("metric").map(|m| MetricDescriptor {
        name: str_field(m, "name"),
        unit: str_field(m, "unit"),
        kind: match m["kind"].as_str().expect("kind") {
            "gauge" => MetricKind::Gauge,
            "sum" => MetricKind::Sum,
            "histogram" => MetricKind::Histogram,
            "exp_histogram" => MetricKind::ExpHistogram,
            "summary" => MetricKind::Summary,
            other => panic!("unknown kind {other}"),
        },
        temporality: match str_field(m, "temporality").as_str() {
            "delta" => Temporality::Delta,
            "cumulative" => Temporality::Cumulative,
            _ => Temporality::Unspecified,
        },
        is_monotonic: m
            .get("is_monotonic")
            .and_then(|v| v.as_bool())
            .unwrap_or(false),
        description: String::new(),
    });
    assert_eq!(
        metric.is_some(),
        signal == Signal::Metrics,
        "vector {j}: metric must be present iff signal is metrics"
    );
    Descriptor {
        signal,
        resource_attrs: kv_from_json(&j["resource_attrs"]),
        resource_schema_url: str_field(j, "resource_schema_url"),
        scope_name: str_field(j, "scope_name"),
        scope_version: str_field(j, "scope_version"),
        scope_schema_url: str_field(j, "scope_schema_url"),
        scope_attrs: kv_from_json(&j["scope_attrs"]),
        metric,
        attrs: kv_from_json(&j["attrs"]),
    }
}

/// Scenario: every vector produced by the independent Python encoder.
/// Guarantees: the Rust encoder and hash reproduce the canonical bytes and series id byte for byte.
#[test]
fn golden_vectors_match() {
    let raw = include_str!("golden/canonical_v1.json");
    let doc: serde_json::Value = serde_json::from_str(raw).expect("json");
    let vectors = doc["vectors"].as_array().expect("vectors");
    assert_eq!(vectors.len(), 33);
    let names: Vec<&str> = vectors
        .iter()
        .map(|v| v["name"].as_str().expect("name"))
        .collect();
    for expect in [
        "nan_quiet",
        "nan_payload",
        "nan_negative",
        "metrics_exp_histogram_delta",
        "metrics_summary",
    ] {
        assert!(names.contains(&expect), "missing vector {expect}");
    }
    for v in vectors {
        let name = v["name"].as_str().expect("name");
        let d = descriptor_from_json(&v["descriptor"]);
        let bytes = canonical_bytes(&d);
        assert_eq!(
            hex_bytes(&bytes),
            v["canonical_hex"].as_str().expect("hex"),
            "bytes of {name}"
        );
        assert_eq!(
            hex(&series_id(&bytes)),
            v["series_id_hex"].as_str().expect("id"),
            "id of {name}"
        );
    }
}

/// Scenario: the vector pair that differs only in the producer attribute.
/// Guarantees: the producer attribute is part of the identity.
#[test]
fn producer_attribute_changes_identity() {
    let raw = include_str!("golden/canonical_v1.json");
    let doc: serde_json::Value = serde_json::from_str(raw).expect("json");
    let find = |n: &str| {
        doc["vectors"]
            .as_array()
            .expect("v")
            .iter()
            .find(|v| v["name"] == n)
            .expect("vector")["series_id_hex"]
            .clone()
    };
    assert_ne!(find("producer_a"), find("producer_b"));
}

fn hex_bytes(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}
