// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

//! Golden vectors generated by tools/gen_golden.py: the canonical identity
//! encoding, the schema fingerprint of every dataset and the `render_v1`
//! storage spellings.

use otel_arrow_dfe_series_lake::canonical::{
    Descriptor, MetricDescriptor, MetricKind, Signal, Temporality, canonical_bytes, hex, series_id,
};
use otel_arrow_dfe_series_lake::config::{DenormType, Denormalize, LakeConfig};
use otel_arrow_dfe_series_lake::schema::{
    Dataset, dataset_schema, schema_fingerprint, schema_rendering,
};
use otel_arrow_dfe_series_lake::value::{Value, body_string, map_string};

fn value_from_json(j: &serde_json::Value) -> Value {
    match j["type"].as_str().expect("type") {
        "null" => Value::Null,
        "str" => Value::Str(j["value"].as_str().expect("str").to_string()),
        "bytes" => Value::Bytes(hex_decode(j["value"].as_str().expect("hex"))),
        "int" => Value::Int(j["value"].as_i64().expect("int")),
        "double" => match j.get("bits") {
            Some(bits) => Value::Double(f64::from_bits(bits.as_u64().expect("bits"))),
            None => Value::Double(j["value"].as_f64().expect("double")),
        },
        "bool" => Value::Bool(j["value"].as_bool().expect("bool")),
        "array" => Value::Array(
            j["items"]
                .as_array()
                .expect("items")
                .iter()
                .map(value_from_json)
                .collect(),
        ),
        "kvlist" => Value::KvList(kv_from_json(&j["entries"])),
        other => panic!("unknown type {other}"),
    }
}

fn kv_from_json(j: &serde_json::Value) -> Vec<(String, Value)> {
    let mut v: Vec<(String, Value)> = j
        .as_array()
        .map(|a| {
            a.iter()
                .map(|e| {
                    (
                        e["key"].as_str().expect("key").to_string(),
                        value_from_json(&e["value"]),
                    )
                })
                .collect()
        })
        .unwrap_or_default();
    v.sort_by(|a, b| a.0.as_bytes().cmp(b.0.as_bytes()));
    v
}

fn hex_decode(s: &str) -> Vec<u8> {
    ::hex::decode(s).expect("hex")
}

fn str_field(j: &serde_json::Value, k: &str) -> String {
    j.get(k).and_then(|v| v.as_str()).unwrap_or("").to_string()
}

fn descriptor_from_json(j: &serde_json::Value) -> Descriptor {
    let signal = match j["signal"].as_str().expect("signal") {
        "logs" => Signal::Logs,
        _ => Signal::Metrics,
    };
    let metric = j.get("metric").map(|m| MetricDescriptor {
        name: str_field(m, "name"),
        unit: str_field(m, "unit"),
        kind: match m["kind"].as_str().expect("kind") {
            "gauge" => MetricKind::Gauge,
            "sum" => MetricKind::Sum,
            "histogram" => MetricKind::Histogram,
            "exp_histogram" => MetricKind::ExpHistogram,
            "summary" => MetricKind::Summary,
            other => panic!("unknown kind {other}"),
        },
        temporality: match str_field(m, "temporality").as_str() {
            "delta" => Temporality::Delta,
            "cumulative" => Temporality::Cumulative,
            _ => Temporality::Unspecified,
        },
        is_monotonic: m
            .get("is_monotonic")
            .and_then(|v| v.as_bool())
            .unwrap_or(false),
        description: String::new(),
    });
    assert_eq!(
        metric.is_some(),
        signal == Signal::Metrics,
        "vector {j}: metric must be present iff signal is metrics"
    );
    Descriptor {
        signal,
        resource_attrs: kv_from_json(&j["resource_attrs"]).into(),
        resource_schema_url: str_field(j, "resource_schema_url"),
        scope_name: str_field(j, "scope_name"),
        scope_version: str_field(j, "scope_version"),
        scope_schema_url: str_field(j, "scope_schema_url"),
        scope_attrs: kv_from_json(&j["scope_attrs"]).into(),
        metric,
        attrs: kv_from_json(&j["attrs"]),
    }
}

/// Scenario: every vector produced by the independent Python encoder.
/// Guarantees: the Rust encoder and hash reproduce the canonical bytes and series id byte for byte.
#[test]
fn golden_vectors_match() {
    let raw = include_str!("golden/canonical_v1.json");
    let doc: serde_json::Value = serde_json::from_str(raw).expect("json");
    let vectors = doc["vectors"].as_array().expect("vectors");
    assert_eq!(vectors.len(), 34);
    let names: Vec<&str> = vectors
        .iter()
        .map(|v| v["name"].as_str().expect("name"))
        .collect();
    for expect in [
        "nan_quiet",
        "nan_payload",
        "nan_negative",
        "neg_zero_double",
        "pos_zero_double",
        "metrics_exp_histogram_delta",
        "metrics_summary",
    ] {
        assert!(names.contains(&expect), "missing vector {expect}");
    }
    for v in vectors {
        let name = v["name"].as_str().expect("name");
        let d = descriptor_from_json(&v["descriptor"]);
        let bytes = canonical_bytes(&d);
        assert_eq!(
            hex::encode(&bytes),
            v["canonical_hex"].as_str().expect("hex"),
            "bytes of {name}"
        );
        assert_eq!(
            hex(&series_id(&bytes)),
            v["series_id_hex"].as_str().expect("id"),
            "id of {name}"
        );
    }
}

/// Scenario: the vector pair differing only in the sign of a zero double.
/// Guarantees: identical canonical bytes and series id (FORMAT.md section 1).
#[test]
fn zero_sign_does_not_change_identity() {
    let raw = include_str!("golden/canonical_v1.json");
    let doc: serde_json::Value = serde_json::from_str(raw).expect("json");
    let find = |n: &str| {
        doc["vectors"]
            .as_array()
            .expect("v")
            .iter()
            .find(|v| v["name"] == n)
            .expect("vector")
            .clone()
    };
    let neg = find("neg_zero_double");
    let pos = find("pos_zero_double");
    // The two vectors really do start from different bit patterns.
    assert_ne!(
        neg["descriptor"]["attrs"][0]["value"]["bits"],
        pos["descriptor"]["attrs"][0]["value"]["bits"],
        "the pair must differ before normalization"
    );
    assert_eq!(neg["canonical_hex"], pos["canonical_hex"]);
    assert_eq!(neg["series_id_hex"], pos["series_id_hex"]);
}

/// Scenario: the vector pair that differs only in the producer attribute.
/// Guarantees: the producer attribute is part of the identity.
#[test]
fn producer_attribute_changes_identity() {
    let raw = include_str!("golden/canonical_v1.json");
    let doc: serde_json::Value = serde_json::from_str(raw).expect("json");
    let find = |n: &str| {
        doc["vectors"]
            .as_array()
            .expect("v")
            .iter()
            .find(|v| v["name"] == n)
            .expect("vector")["series_id_hex"]
            .clone()
    };
    assert_ne!(find("producer_a"), find("producer_b"));
}

/// The schema vectors, each with the dataset and configuration it describes.
fn schema_vectors() -> Vec<(String, Dataset, LakeConfig, String, String)> {
    let raw = include_str!("golden/schema_fingerprint_v1.json");
    let doc: serde_json::Value = serde_json::from_str(raw).expect("json");
    doc["vectors"]
        .as_array()
        .expect("vectors")
        .iter()
        .map(|v| {
            let ds = match v["dataset"].as_str().expect("dataset") {
                "logs/series" => Dataset::LogsSeries,
                "logs/values" => Dataset::LogsValues,
                "metrics/series" => Dataset::MetricsSeries,
                "metrics/values" => Dataset::MetricsValues,
                other => panic!("unknown dataset {other}"),
            };
            let mut cfg = LakeConfig::default();
            cfg.logs.denormalize = v["logs_denormalize"]
                .as_array()
                .expect("logs_denormalize")
                .iter()
                .map(|d| Denormalize {
                    path: d["path"].as_str().expect("path").to_string(),
                    column: d["column"].as_str().expect("column").to_string(),
                    ty: match d["type"].as_str().expect("type") {
                        "string" => DenormType::String,
                        "int64" => DenormType::Int64,
                        "double" => DenormType::Double,
                        "bool" => DenormType::Bool,
                        other => panic!("unknown denormalize type {other}"),
                    },
                })
                .collect();
            (
                v["name"].as_str().expect("name").to_string(),
                ds,
                cfg,
                v["rendering"].as_str().expect("rendering").to_string(),
                v["fingerprint"].as_str().expect("fingerprint").to_string(),
            )
        })
        .collect()
}

/// Scenario: the four default datasets and logs/values with one denormalized column of each type,
/// as the Python generator computes them.
/// Guarantees: each schema renders to the documented text and hashes to the pinned fingerprint.
#[test]
fn schema_fingerprints_match_the_golden_vectors() {
    let vectors = schema_vectors();
    let names: Vec<&str> = vectors.iter().map(|v| v.0.as_str()).collect();
    assert_eq!(
        names,
        [
            "logs/series",
            "logs/values",
            "metrics/series",
            "metrics/values",
            "logs/values+denormalized"
        ]
    );
    for (name, ds, cfg, rendering, fingerprint) in &vectors {
        cfg.validate().expect("golden configuration is valid");
        let schema = dataset_schema(*ds, cfg);
        assert_eq!(&schema_rendering(&schema), rendering, "rendering of {name}");
        assert_eq!(
            &format!("{:016x}", schema_fingerprint(&schema)),
            fingerprint,
            "fingerprint of {name}"
        );
    }
}

/// Scenario: FORMAT.md section 3 lists every golden schema's rendering and fingerprint.
/// Guarantees: each documented rendering and fingerprint is what the code produces.
#[test]
fn format_md_documents_every_schema_rendering() {
    let doc = include_str!("../docs/FORMAT.md");
    for (name, ds, cfg, _, _) in schema_vectors() {
        let schema = dataset_schema(ds, &cfg);
        let fingerprint = format!("{:016x}", schema_fingerprint(&schema));
        let label = format!("`{name}`, fingerprint `{fingerprint}`:");
        let at = doc
            .find(&label)
            .unwrap_or_else(|| panic!("FORMAT.md has no line {label}"));
        let open = "```text\n";
        let body_start =
            at + doc[at..].find(open).expect("text block after the label") + open.len();
        let body_len = doc[body_start..].find("```").expect("closed text block");
        assert_eq!(
            &doc[body_start..body_start + body_len],
            schema_rendering(&schema),
            "documented rendering of {name}"
        );
    }
}

/// Scenario: every `render_v1` vector: each scalar kind, doubles around the layout limits, NaN
/// payloads, infinities, every base64 padding length, nested values.
/// Guarantees: both entry points give exactly the documented strings, as the OTLP JSON encoder
/// spells them.
#[test]
fn render_v1_matches_the_golden_vectors() {
    let raw = include_str!("golden/render_v1.json");
    let doc: serde_json::Value = serde_json::from_str(raw).expect("json");
    let vectors = doc["vectors"].as_array().expect("vectors");
    assert_eq!(vectors.len(), 30);
    for v in vectors {
        let name = v["name"].as_str().expect("name");
        let value = value_from_json(&v["value"]);
        let expected = v["map_value"].as_str();
        assert_eq!(
            map_string(&value).as_deref(),
            expected,
            "map value of {name}"
        );
        assert_eq!(body_string(&value).as_deref(), expected, "body of {name}");
    }
}
